index:
  path: /
  controller: App\Controller\ExchangerController::index

token:
  path: /token
  controller: App\Controller\ExchangerController::token
  condition:  "context.getMethod() in ['POST']"

conversions:
  path: /conversions/{id}
  controller: App\Controller\ExchangerController::conversions
  condition:  "context.getMethod() in ['GET', 'POST']"
  requirements:
    id: '\d+'